### ISSUE TITLE
Add quality option to original image file

### ISSUE THREAD

**Issue by adiramardiani** [mongosoft/yii2-upload-behavior#13]
How to add more option to set quality original image file

**Comment by mongosoft** [comment]
Hello. This behavior doesn't modify the original image.

**Comment by adiramardiani** [comment]
O ow, because imageBehaviour that extends uploadBehaviour
Hmm, supposing indirectly imageBehaviour is extends one layer before uploadBehaviour but there is one layer that allows image manipulation

**Comment by mongosoft** [comment]
Well, you can override this behavior (or use an ```afterUpload``` event) and implement all your manipulations with the original image.
Resize, apply filters, change quality - the list can be continued infinitely. 
I think we should not complicate the basic behavior.

**Comment by adiramardiani** [comment]
Do you have examples source or best practice about that ?

**Comment by mongosoft** [comment]
Well, you can do like this:

```php
class MyUploadImageBehavior extends \mongosoft\file\UploadImageBehavior
{
    public $quality = 90;

    /**
     * @inheritdoc
     */
    protected function afterUpload()
    {
        parent::afterUpload();

        // Fix error "PHP GD Allowed memory size exhausted".
        ini_set('memory_limit', '512M');

        $path = $this->getUploadPath($this->attribute);
        // Update image quality.
        Image::getImagine()->open($path)->save($path, ['quality' => $quality]);
    }
}
```

And usage:
```php
function behaviors()
{
    return [
        [
            'class' => MyUploadImageBehavior::className(),
            'attribute' => 'image',
            'scenarios' => ['insert', 'update'],
            'path' => '@webroot/upload/{id}/images',
            'url' => '@web/upload/{id}/images',
            'quality' => 75,
        ],
    ];
}
```

**Comment by adiramardiani** [comment]
Ok Thanks You :)
