### ISSUE TITLE
Несколько моделей с одним поведением

### ISSUE THREAD

**Issue by maxxi165** [mongosoft/yii2-upload-behavior#2]
Добрый день!
Подскажите пожалуйста, как можно использовать поведение, если на странице размещено несколько экземпляров одной модели с прикрепленным поведением. 
Т.е. например, модель Item c полем image. На странице нужно разместить несколько таких моделей для редактирования (в оригинале - произвольное кол-во) с загрузкой картинок. Вопрос в том, как правильно назначить name для input картинок и как указать атрибут для поведения?

**Comment by mongosoft** [comment]
`name` у `input` может быть произвольным. А вот в поведении должен быть указан атрибут `image`.

Все зависит от того как ты будешь загружать модель. Например в самом простом случае это одна модель и ее атрибуты заполняются методом `load`.

```php
class TestController extends Controller
{
    public function actionCreate()
    {
        $model = new Item();
        $model->setScenario('insert');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'The model has been successfully saved.');
            return $this->refresh();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }
}
```

В представлении:
```php
<?php $form = ActiveForm::begin([
    'options' => ['enctype' => 'multipart/form-data'],
]); ?>
    <?= $form->field($model, 'image')->fileInput() ?>
    <div class="form-group">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
    </div>
<?php ActiveForm::end(); ?>
```

В случае с несколькими моделями можно копнуть в сторону метода `$model->loadMultiple()`.

**Comment by maxxi165** [comment]
С одной моделью я разобрался. Все работает отлично.
За наводку на loadMultiple спасибо. Но оказалось, что этот метод не обрабатывает файлы. Файлы все равно нужно обрабатывать отдельно.

В общем, проблема в следующем. В beforeValidate() поведения файл для модели загружается  строкой

    $this->file = UploadedFile::getInstance($model, $this->attribute);

в комментариях к параметрам написано:

    * @param string $attribute the attribute name. The attribute name may contain array indexes.
    * For example, '[1]file' for tabular file uploading; and 'file[1]' for an element in a file array.

т.е. в случае, когда на странице несколько экземпляров модели с файлами, нужно загружать так:

    $this->file = UploadedFile::getInstance($model, "[$index]" . $this->attribute);

Я проверил - так поведение работает правильно.
Получается нужно вводить в поведение дополнительный атрибут для такого случая. Этот атрибут должен содержать индекс текущей модели на обрабатываемой странице.
Может есть мысли с более элегантным решением? :)
