### ISSUE TITLE
Удаляется значение поля при редактировании.

### ISSUE THREAD

**Issue by SlimSavernake** [mongosoft/yii2-upload-behavior#28]
Удаляется значение поля при редактировании. В базе поле названия картинки становится null, картинки при это остаются на месте.

**Comment by mongosoft** [comment]
Мало информации. Так точно не смогу помочь. В строке https://github.com/mongosoft/yii2-upload-behavior/blob/master/UploadBehavior.php#L166 аттрибут защищен от изменения. Не должно быть такого.
