### ISSUE TITLE
MIT violation

### ISSUE THREAD

**Issue by russianlagman** [mongosoft/yii2-upload-behavior#29]
Чувак, если клонируешь чужие компоненты, распространяемые под MIT лицензией - будь добр, сохраняй авторство.

**Comment by mongosoft** [comment]
@russianlagman а можно ссылку на компонент, клоном которого является этот?

**Comment by russianlagman** [comment]
@mongosoft очевидно, что https://github.com/yii-dream-team/yii2-upload-behavior

**Comment by mongosoft** [comment]
@russianlagman да, не скрою - https://github.com/yii-dream-team/yii2-upload-behavior классное расширение, идея подсмотрена оттуда. Но это совершенно другое расширение и оно не является клоном.

**Comment by russianlagman** [comment]
Иерархия классов, способ работы, нейминг методов - все это ЧАСТИЧНО переработано и нарушает MIT.

**Comment by mongosoft** [comment]
@russianlagman Fixed - все ли сейчас норм?
