### ISSUE TITLE
Class 'backend\models\UploadImageBehavior' not found

### ISSUE THREAD

**Issue by Valonix** [mongosoft/yii2-upload-behavior#5]
Добрый день. Установил через композер расширение.

Модель Post

public function behaviors()
    {
        return [
            'image' => [
                'class' => UploadImageBehavior::className(),
                'attribute' => 'image',
                'scenarios' => ['insert', 'update'],
                'path' => '@webroot/uploads/images/{id}',
                'url' => '@web/uploads/images/{id}',
                'thumbs' => [
                    'thumb' => ['width' => 400, 'quality' => 90],
                    'preview' => ['width' => 200, 'height' => 200],
                ],
            ],
        ];
    }

Ругается "Class 'backend\models\UploadImageBehavior' not found"

И еще вопрос, в мануале у вас 
<div class="col-lg-6">
                
                <?= Html::img($model->getUploadUrl('image'), ['class' => 'img-thumbnail']) ?>
            </div>
            <div class="col-lg-4">
                
                <?= Html::img($model->getThumbUploadUrl('image'), ['class' => 'img-thumbnail']) ?>
            </div>
            <div class="col-lg-2">
                
                <?= Html::img($model->getThumbUploadUrl('image', 'preview'), ['class' => 'img-thumbnail']) ?>
            </div>

 <?= Html::img($model->getUploadUrl('image'), ['class' => 'img-thumbnail']) ?> можете примерно подсказать что из себя представляет данный метод? 

Я так понимаю, это выдергивание пути из базы. Но, как это будет выглядеть если там еще пусто (при создании)

**Comment by timofey-l** [comment]
При объявлении класса нужно полностью указать где его искать:
`\mongosoft\file\UploadImageBehavior::className()`

Полностью пример:
```php
	public function behaviors()
	{
		return [
			'image' => [
				'class' => \mongosoft\file\UploadImageBehavior::className(),
				'attribute' => 'image',
				'scenarios' => ['insert', 'update'],
				'path' => '@webroot/uploads/images/{id}',
				'url' => '@web/uploads/images/{id}',
				'thumbs' => [
					'thumb' => ['width' => 400, 'quality' => 90],
					'preview' => ['width' => 200, 'height' => 200],
				],
			],
		];
	}
```

или в начале файла после `namespace` написать:
```php 
use \mongosoft\file\UploadImageBehavior;
```
Тогда ваш `behaviours()` останется без изменения.

Я так понял вы используете `UploadImageBehavior` в `backend`. И физически файлы будут лежать в директории `backend/web/uploads/images`, которая из `frontend` не будет доступна. Фактически для frontend и backend будут использоваться разные директории, а следовательно и изображения.

Мы у себя сделали так:
* Создали папку `common/uploads` с правами на запись вебсерверу
* В `backend/web` и `frontend/web` (и в др. приложениях если имеются) сделали относительную символьную ссылку на `common/uploads`
* В `fronend` и в `backend` в моделях при описании `UploadImageBehavior` в параметре `path` используем `@common/uploads` вместо `@webroot/uploads`

**Comment by Valonix** [comment]
Да, я из админки гружу фотки, которые мне потом нужно будет получить и в фронтенде. 

"В backend/web и frontend/web (и в др. приложениях если имеются) сделали относительную символьную ссылку на common/uploads"

Это не совсем понял.

**Comment by timofey-l** [comment]
> Это не совсем понял.

Если не понятно по поводу ссылки, то читаем [Википедию](https://ru.wikipedia.org/wiki/%D0%A1%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B0). 
Сделать в linux можно так:
```bash
# переходим в папку с проектом
cd path/to/your/project
# делаем дирректорию в common/uploads
mkdir common/uploads
# переходим в webroot бэкенда
cd backend/web
# создаём символьную ссылку
ln -s ../../common/uploads uploads
# то же самое для frontend
cd ../..
cd frontend/web
ln -s ../../common/uploads uploads
```
После этого появятся "папки" `backend/web/uploads` и `frontend/web/uploads`, содержимое которых будет таким же как и `common/uploads`.
