### ISSUE TITLE
Option saveType, related attributes in placeholded

### ISSUE THREAD

**Issue by ufocoder** [mongosoft/yii2-upload-behavior#8]
I offer to create behavior option called `saveType`, that define how model attribute will be saved, and rewrite behavior according this new feature

This option `saveType` could have value something like that:
* file - you upload file, and attribute will be save as filename - `file.doc`, this value is default
* path - you upload file and attribute will be save as filename with path - `/path/file.doc`

Path value could resolve future problems with related attribute values in placeholders:

For example:

```
    public function getArtist()
    {
        return $this->hasOne(Artist::className(), [ 'id' => 'id_artist' ]);
    }

    public function behaviors()
    {
        return [
            [
                'class'     => UploadBehavior::className(),
                'attribute' => 'image',
                'scenarios' => [ 'default' ],
                'path'      => '@webroot/uploads/{artist.slug}/',
                'url'       => '@web/uploads/{artist.slug}/',
            ],
        ];
    }
```

And if `$model->artist->slug` will be changed, then `$model->getUploadUrl('image')` will resolve with wrong value

**Comment by mongosoft** [comment]
``path``, and ``url`` may be different, what value you want to save in the database?
``@webroot/uploads/{artist.slug}`` or ``@web/uploads/{artist.slug}`` ?

I think, use attribute value that can be changed is a bad idea. And there is no need to complicate the behavior.

**Comment by ufocoder** [comment]
I understand, that's why I create this issue. I think should write about this possible problems in README.md, It will be enougth

**Comment by mongosoft** [comment]
Yes, is's good idea. Cat you create PR?

**Comment by ufocoder** [comment]
Check It. #9

**Comment by mongosoft** [comment]
Thanks!
